language: cpp

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt-get -q install protobuf-compiler libprotobuf-dev libprotoc-dev
    - sh -c 'git clone https://github.com/protobuf-c/protobuf-c.git && cd protobuf-c && ./autogen.sh && ./configure && make && sudo make install'

script:
    - ./autogen.sh
    - ./configure && make distcheck && make clean
